---
title: "Project1"
author: "Saydaliev"
date: "4/1/2020"
output: pdf_document
---
Exploratory Data Analysis Project1
========================


```{r}
library("data.table")
setwd("~/Documents/DataScienceCoursera/Exploratory Data Analysis")
```


```{r}
powerDT<-data.table::fread(input = "data.txt"
                           , na.strings="?")

powerDT[, Global_active_power := lapply(.SD, as.numeric), .SDcols = c("Global_active_power")]
```

# Coverting Data
```{r}
powerDT[, Date := lapply(.SD, as.Date, "%d/%m/%Y"), .SDcols = c("Date")]

```

#Adjust Dates
```{r}
powerDT <- powerDT[(Date >= "2007-02-01") & (Date <= "2007-02-02")]

png("plot1.png", width=480, height=480)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
hist(powerDT[, Global_active_power], main="Global Active Power", 
     xlab="Global Active Power (kilowatts)", ylab="Frequency", col="Red")

dev.off()
```
## Plo2 

```{r}
library("data.table")

setwd("~/Documents/DataScienceCoursera/Exploratory Data Analysis")
```

```{r}
powerDT <- data.table::fread(input = "data.txt"
                             , na.strings="?"
)
```


```{r}
powerDT[, Global_active_power := lapply(.SD, as.numeric), .SDcols = c("Global_active_power")]
```


```{r}
powerDT[, dateTime := as.POSIXct(paste(Date, Time), format = "%d/%m/%Y %H:%M:%S")]
```

```{r}
powerDT <- powerDT[(dateTime >= "2007-02-01") & (dateTime < "2007-02-03")]
```

```{r}
png("plot2.png", width=480, height=480)
```


```{r pressure, echo=FALSE}
plot(x = powerDT[, dateTime]
     , y = powerDT[, Global_active_power]
     , type="l", xlab="", ylab="Global Active Power (kilowatts)")

dev.off()
```

**Plot 3**

```{r}
library("data.table")

setwd("~/Documents/DataScienceCoursera/Exploratory Data Analysis")
```

```{r}
powerDT[, Global_active_power := lapply(.SD, as.numeric), .SDcols = c("Global_active_power")]

powerDT[, dateTime := as.POSIXct(paste(Date, Time), format = "%d/%m/%Y %H:%M:%S")]

powerDT <- powerDT[(dateTime >= "2007-02-01") & (dateTime < "2007-02-03")]

png("plot3.png", width=480, height=480)
```

```{r}
plot(powerDT[, dateTime], powerDT[, Sub_metering_1], type="l", xlab="", ylab="Energy sub metering")
lines(powerDT[, dateTime], powerDT[, Sub_metering_2],col="red")
lines(powerDT[, dateTime], powerDT[, Sub_metering_3],col="blue")
legend("topright"
       , col=c("black","red","blue")
       , c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  ")
       ,lty=c(1,1), lwd=c(1,1))

dev.off()
```

# **PLOT 4**
```{r}
library("data.table")

setwd("~/Documents/DataScienceCoursera/Exploratory Data Analysis")
```

```{r}
powerDT <- data.table::fread(input = "data.txt"
                             , na.strings="?"
)

powerDT[, Global_active_power := lapply(.SD, as.numeric), .SDcols = c("Global_active_power")]

powerDT [, dateTime :=  as.POSIXct(paste(Date, Time), format = "%d/%m/%Y %H:%M:%S")

powerDT <- powerDT[(dateTime >= "2007-02-01") & (dateTime < "2007-02-03")]

png("plot4.png", width=480, height=480)

par(mfrow=c(2,2))
```

**Plot 1**
```{r}
plot(powerDT[, dateTime], powerDT[, Global_active_power], type="l", xlab="", ylab="Global Active Power")
```

**Plot 2**
```{r}
plot(powerDT[, dateTime],powerDT[, Voltage], type="l", xlab="datetime", ylab="Voltage")

```
**Plot 3**
```{r}
plot(powerDT[, dateTime], powerDT[, Sub_metering_1], type="l", xlab="", ylab="Energy sub metering")
lines(powerDT[, dateTime], powerDT[, Sub_metering_2], col="red")
lines(powerDT[, dateTime], powerDT[, Sub_metering_3],col="blue")
legend("topright", col=c("black","red","blue")
       , c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  ")
       , lty=c(1,1)
       , bty="n"
       , cex=.5) 
```


**Plot 4**
```{r}
plot(powerDT[, dateTime], powerDT[,Global_reactive_power], type="l", xlab="datetime", ylab="Global_reactive_power")

dev.off()
```




